# Generated by Django 4.2.4 on 2023-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendTime', models.DateTimeField(verbose_name='sendTime')),
                ('rate', models.IntegerField(verbose_name='rate')),
                ('message', models.CharField(max_length=2000, null=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Forbidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True, verbose_name='username')),
            ],
            options={
                'verbose_name': 'forbidden',
                'verbose_name_plural': 'forbidden',
                'db_table': 'forbidden',
            },
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('loginTime', models.DateTimeField(null=True, verbose_name='loginTime')),
                ('version', models.CharField(max_length=200, verbose_name='version')),
            ],
            options={
                'verbose_name': 'login_info',
                'verbose_name_plural': 'login_info',
                'db_table': 'login_info',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='username')),
                ('gpa', models.TextField(verbose_name='gpa')),
                ('rank', models.TextField(verbose_name='rank')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'score',
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='Standby',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='username')),
                ('loginTime', models.DateTimeField(verbose_name='loginTime')),
                ('between', models.IntegerField(verbose_name='between')),
            ],
            options={
                'verbose_name': 'standby',
                'verbose_name_plural': 'standby',
                'db_table': 'standby',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('studentId', models.CharField(max_length=200, verbose_name='student_id')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='SubjectNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(verbose_name='subject')),
                ('grade', models.IntegerField(verbose_name='grade')),
                ('A', models.IntegerField(verbose_name='a')),
                ('B', models.IntegerField(verbose_name='b')),
                ('C', models.IntegerField(verbose_name='c')),
                ('D', models.IntegerField(verbose_name='d')),
                ('E', models.IntegerField(verbose_name='e')),
                ('sum', models.IntegerField(verbose_name='sum')),
            ],
            options={
                'verbose_name': 'subject_number',
                'verbose_name_plural': 'subject_number',
                'db_table': 'subject_number',
            },
        ),
        migrations.CreateModel(
            name='White',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
            ],
            options={
                'verbose_name': 'white',
                'verbose_name_plural': 'white',
                'db_table': 'white',
            },
        ),
    ]
